solax_sensor:
  sensor:
    ###################################
    # Solax X1 Hybrid G4 Rest Sensors #
    # Added:
    # 12 - Feed In Min SOC %
    # 13 - Feed In Charge from grid to %
    # 14 - battery heating enable
    # 15 - heat start
    # 16 - heat end
    # 17 - heat start 2
    # 18 - heat end 2
    ###################################

    ### Solax Local REST sensor ###
    - platform: rest
      scan_interval: 60
      resource: !secret solax_local_ip
      payload: !secret solax_local_realtime_payload
      method: POST
      name: "solax_rest_local"
      json_attributes:
        - sn
        - ver
        - type
        - Data
        - Information
      value_template: "OK" # dummy value, not used; avoids the "State max length is 255 characters" error

    #    ### Solax Local REST settings Self Use###
    - platform: rest
      scan_interval: 3601
      unique_id: d2e621bd-dada-4eab-984f-cd524cdbee68
      resource: !secret solax_local_ip
      payload: !secret solax_local_settings_payload
      method: POST
      name: "solax_rest_local_settings"
      # Unfortunately settings are not returned as a JSON document but an array of numbers, so having to pick just the relevant to avoid the max 255 chars limit
      # 0 - Self Use Min SOC %
      # 1 - Self Use Charge from grid (0 for disabled, 1 for enabled)
      # 2 - Self Use Charge from grid to %
      # 3 - Forced charge start
      # 4 - Forced charge end
      # 5 - Allowed discharge start
      # 6 - Allowed discharge end
      # 7 - Charge/discharge Period2 Enabled (0 for disabled, 1 for enabled)
      # 8 - Forced charge start (2nd)
      # 9 - Forced charge end (2nd)
      # 10 - Inverter mode - 0: self use, 1: feed in priority, 2: back up, 3: manual
      # 11 - Manual mode behaviour - 0: do nothing, 1: forced charge, 2: forced discharge
      # 12 - Feed In Min SOC %
      # 13 - Feed In Charge from grid to %
      # 14 - battery heating enable
      # 15 - heat start
      # 16 - heat end
      # 17 - heat start 2
      # 18 - heat end 2
      value_template: "{{ '[' ~
        value.split(',')[28] ~ ',' ~
        value.split(',')[29] ~ ',' ~
        value.split(',')[30] ~ ',' ~
        value.split(',')[36] ~ ',' ~
        value.split(',')[37] ~ ',' ~
        value.split(',')[38] ~ ',' ~
        value.split(',')[39] ~ ',' ~
        value.split(',')[40] ~ ',' ~
        value.split(',')[41] ~ ',' ~
        value.split(',')[42] ~ ',' ~
        value.split(',')[27] ~ ',' ~
        value.split(',')[35] ~ ',' ~
        value.split(',')[31] ~ ',' ~
        value.split(',')[32] ~ ',' ~
        value.split(',')[115] ~ ',' ~
        value.split(',')[116] ~ ',' ~
        value.split(',')[117] ~ ',' ~
        value.split(',')[118] ~ ',' ~
        value.split(',')[119] ~ ']' }}"
