solax_zappi_octopus_input_datetime:
  input_datetime:
    #########################################
    #Solax UI
    # change log
    # v2.1 added battery warmer and renamed solar threshold
    #########################################
    solax_battery_start_discharge_time:
      name: Battery Start Discharge Time
      has_date: false
      has_time: true
      icon: mdi:clock-start

    solax_battery_stop_discharge_time:
      name: Battery Stop Discharge Time
      has_date: false
      has_time: true
      icon: mdi:clock-end

    solax_battery_start_charge_time:
      name: Battery Start Charge Time
      has_date: false
      has_time: true
      icon: mdi:clock-start

    solax_battery_stop_charge_time:
      name: Battery Stop Charge Time
      has_date: false
      has_time: true
      icon: mdi:clock-end

    solax_start_charge_2:
      name: Start Charge 2
      has_date: false
      has_time: true
      icon: mdi:clock-start

    solax_stop_charge_2:
      name: Stop Charge 2
      has_date: false
      has_time: true
      icon: mdi:clock-end

    solax_battery_start_heat_time:
      name: Battery Start Heating Time
      has_date: false
      has_time: true
      icon: mdi:clock-start

    solax_battery_stop_heat_time:
      name: Battery Stop Heating Time
      has_date: false
      has_time: true
      icon: mdi:clock-end

    solax_start_heat_2:
      name: Start Heating 2
      has_date: false
      has_time: true
      icon: mdi:clock-start

    solax_stop_heat_2:
      name: Stop Heating 2
      has_date: false
      has_time: true
      icon: mdi:clock-end

    #Time that ev can start charge +/- wobble
    don_t_charge_ev_before_time:
      name: Don't charge EV before time
      has_date: false
      has_time: true
