###############################
# V5.0.1    Added Battery Export Margin Delta (minutes)
#           This is to account for sometimes Battery SoC is not quite linear
#           and also not always accurate
# V3.0.0 Added Units
###############################
solax_zappi_octopus_input_number:
  input_number:
    # Solax UI
    sun_degrees_above_horizon:
      name: Sunset degrees above horizon
      unit_of_measurement: "Degrees"
      min: 0
      max: 20
      mode: box
      step: 0.5
      icon: mdi:weather-sunset-down
    solax_feed_in_charge_to_soc:
      name: Feed In Charge to SoC
      unit_of_measurement: "%"
      #initial: 90
      min: 30
      max: 100
      step: 1
      mode: slider
      icon: mdi:battery-charging-100
    solax_feed_in_battery_min_soc:
      name: Feed In Min SoC
      unit_of_measurement: "%"
      #initial: 15
      min: 10
      max: 100
      step: 1
      mode: slider
      icon: mdi:battery-charging-20
    solax_selfuse_charge_to_soc:
      name: Self Use Charge to SoC
      unit_of_measurement: "%"
      #initial: 90
      min: 30
      max: 100
      step: 1
      mode: slider
      icon: mdi:battery-charging-100
    solax_selfuse_battery_min_soc:
      name: Self Use Min SoC
      unit_of_measurement: "%"
      #initial: 15
      min: 10
      max: 100
      step: 1
      mode: slider
      icon: mdi:battery-charging-20
    #Manual forced discharge limit
    solax_manual_forced_discharge_limit_soc:
      name: Daily/Forced Discharge SoC
      unit_of_measurement: "%"
      #initial: 18
      min: 10
      max: 80
      step: 1
      mode: box
      icon: mdi:battery-20
    #Manual forced discharge limit
    solax_discharge_limit_soc_before_ev:
      name: Discharge to SoC (Before charging EV)
      unit_of_measurement: "%"
      #initial: 18
      min: 10
      max: 100
      step: 1
      mode: box
      icon: mdi:battery-20
    #Default Min SoC discharge limit
    solax_default_discharge_limit_soc:
      name: Default Minimum SoC
      unit_of_measurement: "%"
      #initial: 18
      min: 10
      max: 100
      step: 1
      mode: box
      icon: mdi:battery-40
    #Default Charge to SoC
    solax_default_charge_to_limit_soc:
      name: Default Charge to SoC
      unit_of_measurement: "%"
      #initial: 18
      min: 15
      max: 100
      step: 1
      mode: box
      icon: mdi:battery-90
    # ev_battery size (used for checking if it's possible to get a dispatch if you want to discharge battery prior to charging EV)
    ev_battery_size:
      name: Registered EV Battery Size
      unit_of_measurement: "kWh"
      #initial: 87
      min: 10
      max: 200
      step: 1
      mode: box
      icon: mdi:car-battery
    # Delay automation when EV first connected
    delay_when_ev_connected:
      name: Delay after EV is Connected
      unit_of_measurement: "minutes"
      min: 0
      max: 15
      step: 1
      mode: box
      icon: mdi:car-clock
    battery_export_margin_delta:
      name: Export Margin Delta
      min: 0
      max: 15
      step: 1
      mode: box
      unit_of_measurement: "minutes"
      icon: mdi:timer-plus-outline
    solax_battery_capacity:
      name: Solax Battery Size
      unit_of_measurement: "kWh"
      min: 3.1
      max: 12.3
      step: .1
      mode: box
      icon: mdi:home-battery
    solax_inverter_capacity:
      name: Solax Inverter Size
      unit_of_measurement: "kWh"
      min: 1
      max: 10
      step: .1
      mode: box
      icon: mdi:home-lightning-bolt-outline
    solax_battery_soh_stored:
      name: Solax Battery SoH Stored
      min: 0
      max: 100
      step: 0.1
      mode: box
      icon: mdi:skull-crossbones
      unit_of_measurement: "%"