solax_zappi_octopus_input_boolean:
  input_boolean:
    ###########################################
    # Solax Zappi Octopus UI
    # v3.7 Pre-emptive battery exports
    # v3.1 Solax System on/off State
    # v3.0 Discharge Solax before EV charge
    # v2.1 Battery Warmer
    ###########################################
    # mute notifications
    solax_zappi_octopus_control_notifications:
      name: Automation Notifications
      icon: mdi:bell
    #zappi_eco_mode_overriden switch if you switch this on automations will ignore other criteria like scheduled charge time and allow Octopus to create schedules during the day
    #Use this when you want to charge the car during the day when octopus has surplus.
    zappi_eco_mode_override:
      name: Octopus Schedule at Anytime 
      icon: mdi:ev-station
    #Prevent EV charging before sunset
    solar_export_priority:
      name: Octopus Schedule after Sun Elevation Threshold
      icon: mdi:solar-power
    #Prevent EV discharging Solax Battery
    ev_solax_battery_drain:
      name: Prevent Zappi Draining Battery
      icon: mdi:battery-10
    #use grid during octopus dispatch
    use_grid_during_octopus_dispatch:
      name: Use Grid During Octopus Dispatch
      icon: mdi:transmission-tower-import
    #Solax automation running
    solax_automation_running:
      name: Solax Automation Running
      icon: mdi:robot-angry
    #A secondary charge period usually left off
    solaxchargeperiod2:
      name: Charge Period 2
      icon: mdi:battery-clock
    #A secondary charge period usually left off
    self_use_enable_charge_from_grid:
      name: Self Use Enable Charge From Grid
      icon: mdi:transmission-tower-import
    #A secondary charge period usually left off
    battery_heat_enable:
      name: Battery Heating
      icon: mdi:heating-coil
    #Export battery switch is used to determine if the remainder of solax battery can be dumped back to the grid during off peak
    export_battery:
      name: Nightly Battery Export
      icon: mdi:battery-arrow-down
    #Attempt to discharge battery before programmed EV charge time /cheap rate time
    pre_emptive_export_battery:
      name: Pre-emptive Battery Exports
      icon: mdi:battery-arrow-down    
    #Attempt to discharge battery before charging EV
    export_battery_prior:
      name: Export Battery Before Charging EV
      icon: mdi:battery-arrow-down
    #Manual Export
    export_battery_manual:
      name: Export Battery Manual
      icon: mdi:battery-arrow-down
    # solax System on/off
    solax_system_enable:
      name: Solax System Enable
      icon: mdi:home-battery

    #Notify a mobile device_tracker
    nofify_mobile:
      name: Notify mobile?
      icon: mdi:bell-plus
    # Zappi always left in ECO mode when connected
    zappi_eco_always:
      name: Zappi always in ECO+ Mode (when connected)
      icon: mdi:leaf
    # Switch to indicate if a saving session is in progress
    saving_session_active:
      name: Saving Session In Progress
      icon: mdi:leaf
    solax_octopus_hide_settings:
      name: Hide Settings
      icon: mdi:eye-off
    solax_octopus_hide_energy:
      name: Hide Energy Charts
      icon: mdi:eye-off
    solax_octopus_hide_power:
      name: Hide Power Charts
      icon: mdi:eye-off
    solax_octopus_hide_stats:
      name: Hide Stats Charts
      icon: mdi:eye-off
    ###########################################
