solax_zappi_octopus_input_select:
  input_select:
    # automations rely on the order and index position for Self Use, Feed In and Manual.
    # Do not change unless you really know what you are doing
    solax_work_mode:
      name: Work Mode
      options:
        - Self Use
        - Feed In Priority
        - Backup Mode
        - Manual
        - Peakshaving
        - Enhanced TOU
      #  initial: Feed In Priority
      icon: mdi:auto-mode
    solax_default_mode:
      name: Default Mode After Discharge
      options:
        - Self Use
        - Feed In Priority
      #initial: Self Use
      icon: mdi:weather-sunny-alert
    solax_manual_modes:
      name: Manual Modes
      options:
        - Do Nothing
        - Force Charge
        - Force Discharge
      icon: mdi:battery-outline
    solax_battery_heat_level:
      name: Battery Heat Level
      options:
        - '0'
        - '1'
        - '2'
      icon: mdi:heating-coil
    solax_automation_notification_devices:
      name: Notify Mobile Device
      options:
        - ' '
      icon: mdi:cellphone-sound
    zappi_default_behaviour:
      name: Zappi Default Behaviour
      options:
        - Full Octopus Control
        - Charge After Sunset
        - Charge After Set Time
      icon: mdi:ev-station
    solax_zappi_octopus_notification_list:
      name: Notification to Exclude
      options:
        - ' '
        - EV Charging Started
        - Octopus Paused Charging.
        - EV Connected - Waiting for Octopus schedule
        - EV Finished Charging
        - EV Disconnected
        - Manual Battery Export Started
        - Manual Battery Export Finished
        - Daily Battery Export Started
        - Daily Battery Export Finished
        - Nightly Battery Export Started
        - Nightly Battery Export Finished
        - Battery Export in Dispatch Gap - Started
        - Battery Export in Dispatch Gap - Finished
        - Cheap Rate
        - Peak Rate
      icon: mdi:alert






