
######################################################
# v1.0.0 tariff events for utility meters and triggering events
######################################################
solax_loads_utilitymeter_tariff:
  template:
    ######################################################
    # Generate tariff events and selects utility meter settings when:
    #   dispatching changes
    #   free electric sessions moved to saving sessions package
    #   between 05:30 and 23:30
    ######################################################
    - trigger:
        # - trigger: time
        #   at: sensor.octopus_free_electricity_start
        # - trigger: state
        #   entity_id: binary_sensor.octopus_intelligent_dispatching
        #   from: "off"
        #   to: "on"
        # - trigger: state
        #   entity_id: binary_sensor.octopus_energy_electricity_off_peak
        #   from: "off"
        #   to: "on"
        - trigger: state
          entity_id: sensor.octopus_tariff_state
          not_to:
            - unavailable
            - unknown
      action:
        - event: octopus_tariff
          event_data:
            tariff: >
              {{ states('sensor.octopus_tariff_state') }}
            time: >
              {{now()|as_datetime}}
        - service: select.select_option
          data:
            entity_id: select.daily_grid_import
            option: >
              {{ states('sensor.octopus_tariff_state') }}
        - service: select.select_option
          data:
            entity_id: select.monthly_grid_import
            option: >
              {{ states('sensor.octopus_tariff_state') }}

    # - trigger:
    #     - trigger: state
    #       entity_id: binary_sensor.free_electricity_today
    #       from: "on"
    #       to: "off"
    #       for:
    #         minutes: 2
    #     - trigger: state
    #       entity_id: binary_sensor.octopus_intelligent_dispatching
    #       from: "on"
    #       to: "off"
    #     - trigger: state
    #       entity_id: binary_sensor.octopus_energy_electricity_off_peak
    #       from: "on"
    #       to: "off"
    #     - trigger: state
    #       entity_id: sensor.octopus_tariff_state
    #       not_to:
    #         - unavailable
    #         - unknown
    #   action:
    #     - event: octopus_tariff
    #       event_data:
    #         tariff: >
    #           {{ states('sensor.octopus_tariff_state') }}
    #         time: >
    #           {{now()|as_datetime}}
    #     - service: select.select_option
    #       data:
    #         entity_id: select.daily_grid_import
    #         option: >
    #           {{ states('sensor.octopus_tariff_state') }}
    #     - service: select.select_option
    #       data:
    #         entity_id: select.monthly_grid_import
    #         option: >
    #           {{ states('sensor.octopus_tariff_state') }}