#################################################################
#Solax
# You must replace YYYYYYYYYY with your own solax registration number
# You must replace the static IP with your own
# Battery warming added
# WARNING: NAMES ARE DIFFERENT TO OTHER IMPLEMENTATIONS
#################################################################
solax_local_ip: http://192.168.xxx.xxx/ # IP of solax module

solax_local_realtime_payload: "optType=ReadRealTimeData&pwd=YYYYYYYYYY"
