    ###################################
    # Solax X1 Hybrid G4 Rest Sensors #
    # v1.2.0 Increased reliabilty
    # v1.0.1 Added a safe sensor to prevent dodgy values when network glitches etc
    ###################################
solax_realtime_sensor:
  sensor:
    ### Solax Local REST sensor ###
    - platform: rest
      scan_interval: 60
      resource: !secret solax_local_ip
      payload: !secret solax_local_realtime_payload
      method: POST
      name: "solax_rest_local"
      json_attributes:
        - sn
        - ver
        - type
        - Data
        - Information
      value_template: >
          {{ "OK" }}

  ############################################
  # Solax Local proxy to normalize state #
  ############################################
  template:
    - sensor:
        - name: "solax_rest_local_safe"
          state: >
            {% set s = states('sensor.solax_rest_local') %}
            {% if s in ['unavailable', 'unknown', '', 'none', 'None'] %}
              None
            {% else %}
              {{ s }}
            {% endif %}
          attributes:
            sn: "{{ state_attr('sensor.solax_rest_local', 'sn') }}"
            ver: "{{ state_attr('sensor.solax_rest_local', 'ver') }}"
            type: "{{ state_attr('sensor.solax_rest_local', 'type') }}"
            Data: "{{ state_attr('sensor.solax_rest_local', 'Data') }}"
            Information: "{{ state_attr('sensor.solax_rest_local', 'Information') }}"

