solax_zappi_octopus_ui_input_datetime:
  input_datetime:
    #########################################
    #Solax UI
    # change log
    # v5.4.0  added daily_battery_export_time
    #.        added pre_daily_battery_export_time
    # v2.1    added battery warmer and renamed solar threshold
    #########################################
    solax_battery_start_discharge_time:
      name: Battery Start Discharge Time
      has_date: false
      has_time: true
      icon: mdi:clock-start

    solax_battery_stop_discharge_time:
      name: Battery Stop Discharge Time
      has_date: false
      has_time: true
      icon: mdi:clock-end

    solax_battery_start_charge_time:
      name: Battery Start Charge Time
      has_date: false
      has_time: true
      icon: mdi:clock-start

    solax_battery_stop_charge_time:
      name: Battery Stop Charge Time
      has_date: false
      has_time: true
      icon: mdi:clock-end

    solax_start_charge_2:
      name: Start Charge 2
      has_date: false
      has_time: true
      icon: mdi:clock-start

    solax_stop_charge_2:
      name: Stop Charge 2
      has_date: false
      has_time: true
      icon: mdi:clock-end

    solax_battery_start_heat_time:
      name: Battery Start Heating Time
      has_date: false
      has_time: true
      icon: mdi:clock-start

    solax_battery_stop_heat_time:
      name: Battery Stop Heating Time
      has_date: false
      has_time: true
      icon: mdi:clock-end

    solax_start_heat_2:
      name: Start Heating 2
      has_date: false
      has_time: true
      icon: mdi:clock-start

    solax_stop_heat_2:
      name: Stop Heating 2
      has_date: false
      has_time: true
      icon: mdi:clock-end

    #Time that ev can start charge +/- wobble
    don_t_charge_ev_before_time:
      name: Octopus Schedule After
      has_date: false
      has_time: true

    daily_battery_export_time:
      name: Daily Battery Export Time
      has_time: true

    pre_daily_battery_export_time:
      name: Pre Daily Battery Export Time
      has_date: true
      has_time: true

    pre_daily_battery_export_time2:
      name: Pre Daily Battery Export Time2
      has_date: true
      has_time: true

    pre_nightly_battery_export_time:
      name: Pre Nightly Battery Export Time
      has_date: true
      has_time: true
