########################################################################################
# AUTOMATION 5005 
# 1. This is 5005 only you need 5001 5002 5003 and 5004. files are kept seperate in repo 
# for ease of maintenance
# 2. Copy and Paste into your automations.yaml
# 3. Requires new dashboard update see /dasboards/Solax & Octopus Settings
########################################################################################
alias: Solax Zappi Octopus Control - Notifier
description: V2.0
triggers:
  - trigger: event
    event_type: Solax Zappi Octopus Control
    event_data:
      class: normal
    id: Normal
  - trigger: event
    event_type: Solax Zappi Octopus Control
    event_data:
      class: high
    id: High
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - High
          - condition: state
            entity_id: input_boolean.solax_zappi_octopus_control_notifications
            state: "off"
        sequence:
          - action: persistent_notification.create
            data:
              title: "{{trigger.event.data.title}}"
              message: "{{trigger.event.data.message}}"
          - if:
              - condition: template
                value_template: >-
                  {{states('input_boolean.nofify_mobile') == 'on' and
                  states('input_select.solax_automation_notification_devices')
                  != 'None'}}
            then:
              - action: >-
                  {% set notify = "notify." +
                  states('input_select.solax_automation_notification_devices')
                  -%} {{notify}}
                metadata: {}
                data:
                  title: "{{trigger.event.data.title}}"
                  message: "{{trigger.event.data.message}}"
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id:
                  - Normal
              - condition: trigger
                id:
                  - High
          - condition: state
            entity_id: input_boolean.solax_zappi_octopus_control_notifications
            state: "on"
        sequence:
          - action: persistent_notification.create
            data:
              title: "{{trigger.event.data.title}}"
              message: "{{trigger.event.data.message}}"
          - if:
              - condition: template
                value_template: >-
                  {{states('input_boolean.nofify_mobile') == 'on' and
                  states('input_select.solax_automation_notification_devices')
                  != 'None'}}
            then:
              - action: >-
                  {% set notify = "notify." +
                  states('input_select.solax_automation_notification_devices')
                  -%} {{notify}}
                metadata: {}
                data:
                  title: "{{trigger.event.data.title}}"
                  message: "{{trigger.event.data.message}}"
mode: queued
max: 10

