house_power_input_datetime:
  input_datetime:
    power_stat_start_time:
      name: "Start Time"
      has_date: false
      has_time: true

    power_stat_end_time:
      name: "End Time"
      has_date: false
      has_time: true


