####################################
# v1.3.0 Added attribute to show if cached sensor values are used
# v1.2.0 Tidy up
####################################

solax_control_templates:
  template:
    - trigger:
        - platform: state
          entity_id: sensor.solax_rest_local_settings
      sensor:
        - name: solax_local_settings
          state: >-
            {% set rest_state = states('sensor.solax_rest_local_settings') %}
            {% set rest_last_updated = states.sensor.solax_rest_local_settings.last_updated | default(0) %}
            {% if rest_state not in ['unavailable', 'unknown', 'none'] %}
              {{ as_timestamp(rest_last_updated) | timestamp_custom('%Y-%m-%d %H:%M:%S') }}
            {% else %}
              {{ state_attr('sensor.solax_local_settings','last_valid_update')
                  | default('unknown') }}
            {% endif %}
          attributes:
            Data: >-
              {% set rest_state = states('sensor.solax_rest_local_settings') %}
              {% if rest_state not in ['unavailable', 'unknown', 'none'] %}
                {{ rest_state }}
              {% else %}
                {{ state_attr('sensor.solax_local_settings','Data') }}
              {% endif %}
            using_cache: >-
              {% set rest_state = states('sensor.solax_rest_local_settings') %}
              {{ rest_state in ['unavailable', 'unknown', 'none'] }}
            last_valid_update: >-
              {% set rest_state = states('sensor.solax_rest_local_settings') %}
              {% set rest_last_updated = states.sensor.solax_rest_local_settings.last_updated | default(0) %}
              {% if rest_state not in ['unavailable', 'unknown', 'none'] %}
                {{ as_timestamp(rest_last_updated) | timestamp_custom('%Y-%m-%d %H:%M:%S') }}
              {% else %}
                {{ state_attr('sensor.solax_local_settings','last_valid_update')
                    | default('unknown') }}
              {% endif %}
        ######################################################
        # Solax Local Settings
        ######################################################
    - sensor:
        # System on/off
        - name: "Solax Local System State"
          unique_id: solax_local_system_state
          state: >
            {% set d = state_attr('sensor.solax_local_settings','Data') or [] %}
            {{ (d[19] | int(0)) == 1 }}
          #device_class: power
          icon: mdi:home-switch
          availability: "{{ state_attr('sensor.solax_local_settings','Data') is not none }}"

        # Battery discharge min (%) (Self Use Mode)
        - name: "Solax Local SelfUse Battery Min SoC"
          unique_id: solax_local_selfuse_battery_min_soc
          state: >
            {% set d = state_attr('sensor.solax_local_settings','Data') or [] %}
            {{ d[0] | int(0) }}
          unit_of_measurement: "%"
          state_class: measurement
          device_class: battery
          icon: mdi:battery-20
          availability: "{{ state_attr('sensor.solax_local_settings','Data') is not none }}"

        # Battery charge from grid switch (Self Use Mode)
        - name: "Solax Local Self Use Battery Charge From Grid"
          unique_id: solax_local_selfuse_battery_grid_enabled
          state: >
            {% set d = state_attr('sensor.solax_local_settings','Data') or [] %}
            {{ d[1] | int(0) }}
          #device_class: power
          icon: mdi:battery-arrow-up
          availability: "{{ state_attr('sensor.solax_local_settings','Data') is not none }}"

        # Battery charge level to (%) from grid (Self Use Mode)
        - name: "Solax Local SelfUse Battery Chrg Frm Grd To"
          unique_id: solax_local_selfuse_battery_chrg_frm_grd_to
          state: >
            {% set d = state_attr('sensor.solax_local_settings','Data') or [] %}
            {{ d[2] | int(94) }}
          unit_of_measurement: "%"
          state_class: measurement
          device_class: battery
          icon: mdi:battery-charging-90
          availability: "{{ state_attr('sensor.solax_local_settings','Data') is not none }}"

        # Battery discharge min (%) (Feed In Mode)
        - name: "Solax Local Feed In Battery Min SoC"
          unique_id: solax_local_feed_in_battery_min_soc
          state: >
            {% set d = state_attr('sensor.solax_local_settings','Data') or [] %}
            {{ d[12] | int(0) }}
          unit_of_measurement: "%"
          state_class: measurement
          device_class: battery
          icon: mdi:battery-20
          availability: "{{ state_attr('sensor.solax_local_settings','Data') is not none }}"

        # Battery charge level to (%) from grid (Feed In Mode)
        - name: "Solax Local Feed In Battery Charge From Grid To"
          unique_id: solax_local_feed_in_battery_charge_from_grid_to
          state: >
            {% set d = state_attr('sensor.solax_local_settings','Data') or [] %}
            {{ d[13] | int(0) }}
          unit_of_measurement: "%"
          state_class: measurement
          device_class: battery
          icon: mdi:battery-charging-90
          availability: "{{ state_attr('sensor.solax_local_settings','Data') is not none }}"

        # Battery settings charge/discharge (period 1)
        - name: "Solax Local Battery Setting Start Charge"
          unique_id: solax_local_battery_setting_start_charge
          state: >
            {% set d = state_attr('sensor.solax_local_settings','Data') or [] %}
            {{ '%02d' % (d[3] % 256 | int(0)) }}:{{ '%02d' % (d[3] / 256 | int(0)) }}
          icon: mdi:clock-start
          availability: "{{ state_attr('sensor.solax_local_settings','Data') is not none }}"

        - name: "Solax Local Battery Setting Stop Charge"
          unique_id: solax_local_battery_setting_stop_charge
          state: >
            {% set d = state_attr('sensor.solax_local_settings','Data') or [] %}
            {{ '%02d' % (d[4] % 256 | int(0)) }}:{{ '%02d' % (d[4] / 256 | int(0)) }}
          icon: mdi:clock-end
          availability: "{{ state_attr('sensor.solax_local_settings','Data') is not none }}"

        - name: "Solax Local Battery Setting Start Discharge"
          unique_id: solax_local_battery_setting_start_discharge
          state: >
            {% set d = state_attr('sensor.solax_local_settings','Data') or [] %}
            {{ '%02d' % (d[5] % 256 | int(0)) }}:{{ '%02d' % (d[5] / 256 | int(0)) }}
          icon: mdi:clock-start
          availability: "{{ state_attr('sensor.solax_local_settings','Data') is not none }}"

        - name: "Solax Local Battery Setting Stop Discharge"
          unique_id: solax_local_battery_setting_stop_discharge
          state: >
            {% set d = state_attr('sensor.solax_local_settings','Data') or [] %}
            {{ '%02d' % (d[6] % 256 | int(0)) }}:{{ '%02d' % (d[6] / 256 | int(0)) }}
          icon: mdi:clock-end
          availability: "{{ state_attr('sensor.solax_local_settings','Data') is not none }}"

        # Battery settings charge/discharge (period 2)
        - name: "Solax Local Battery Setting Start Charge 2"
          unique_id: solax_local_battery_setting_start_charge2
          state: >
            {% set d = state_attr('sensor.solax_local_settings','Data') or [] %}
            {{ '%02d' % (d[8] % 256 | int(0)) }}:{{ '%02d' % (d[8] / 256 | int(0)) }}
          icon: mdi:clock-start
          availability: "{{ state_attr('sensor.solax_local_settings','Data') is not none }}"

        - name: "Solax Local Battery Setting Stop Charge 2"
          unique_id: solax_local_battery_setting_stop_charge2
          state: >
            {% set d = state_attr('sensor.solax_local_settings','Data') or [] %}
            {{ '%02d' % (d[9] % 256 | int(0)) }}:{{ '%02d' % (d[9] / 256 | int(0)) }}
          icon: mdi:clock-end
          availability: "{{ state_attr('sensor.solax_local_settings','Data') is not none }}"

        - name: "Solax Local Battery ChD2 Enabled"
          unique_id: solax_local_battery_chd2_enabled
          state: >
            {% set d = state_attr('sensor.solax_local_settings','Data') or [] %}
            {{ (d[7] | int(0)) == 1 }}
          #device_class: power
          icon: mdi:battery-arrow-up
          availability: "{{ state_attr('sensor.solax_local_settings','Data') is not none }}"

        # Inverter working mode
        - name: "Solax Local Inverter Mode"
          unique_id: solax_local_inverter_mode
          device_class: enum
          state: >
            {% set mapper = {0:'Self Use',1:'Feed In Priority',2:'Back Up',3:'Manual'} %}
            {% set d = state_attr('sensor.solax_local_settings','Data') or [] %}
            {% set val = d[10] | int(0) %}
            {{ mapper[val] if val in mapper else 'Unknown' }}
          icon: mdi:sun-compass
          availability: "{{ state_attr('sensor.solax_local_settings','Data') is not none }}"

        # Inverter manual mode
        - name: "Solax Local Manual Mode Behaviour"
          unique_id: solax_local_manual_mode_behaviour
          device_class: enum
          state: >
            {% set mapper = {0:'Do Nothing',1:'Force Charge',2:'Force Discharge'} %}
            {% set d = state_attr('sensor.solax_local_settings','Data') or [] %}
            {% set val = d[11] | int(0) %}
            {{ mapper[val] if val in mapper else 'Unknown' }}
          availability: "{{ state_attr('sensor.solax_local_settings','Data') is not none }}"

        # Battery heat enabled
        - name: "Solax Local Battery Heat Enabled"
          unique_id: solax_local_battery_heat_enabled
          state: >
            {% set d = state_attr('sensor.solax_local_settings','Data') or [] %}
            {{ (d[14] | int(0)) == 1 }}
          #device_class: power
          icon: mdi:radiator
          availability: "{{ state_attr('sensor.solax_local_settings','Data') is not none }}"

        # Battery heat level
        - name: "Solax Local Battery Heat Level"
          unique_id: solax_local_battery_heat_level
          state: >
            {% set d = state_attr('sensor.solax_local_settings','Data') or [] %}
            {{ d[20] | int(0) }}
          state_class: measurement
          #device_class: power
          icon: mdi:radiator
          availability: "{{ state_attr('sensor.solax_local_settings','Data') is not none }}"

        # Battery heat period 1
        - name: "Solax Local Battery Heat Start"
          unique_id: solax_local_battery_heat_start
          state: >
            {% set d = state_attr('sensor.solax_local_settings','Data') or [] %}
            {{ '%02d' % (d[15] % 256 | int(0)) }}:{{ '%02d' % (d[15] / 256 | int(0)) }}
          icon: mdi:clock-start
          availability: "{{ state_attr('sensor.solax_local_settings','Data') is not none }}"

        - name: "Solax Local Battery Heat Stop"
          unique_id: solax_local_battery_heat_stop
          state: >
            {% set d = state_attr('sensor.solax_local_settings','Data') or [] %}
            {{ '%02d' % (d[16] % 256 | int(0)) }}:{{ '%02d' % (d[16] / 256 | int(0)) }}
          icon: mdi:clock-end
          availability: "{{ state_attr('sensor.solax_local_settings','Data') is not none }}"

        # Battery heat period 2
        - name: "Solax Local Battery Heat Start 2"
          unique_id: solax_local_battery_heat_start_2
          state: >
            {% set d = state_attr('sensor.solax_local_settings','Data') or [] %}
            {{ '%02d' % (d[17] % 256 | int(0)) }}:{{ '%02d' % (d[17] / 256 | int(0)) }}
          icon: mdi:clock-start
          availability: "{{ state_attr('sensor.solax_local_settings','Data') is not none }}"

        - name: "Solax Local Battery Heat Stop 2"
          unique_id: solax_local_battery_heat_stop_2
          state: >
            {% set d = state_attr('sensor.solax_local_settings','Data') or [] %}
            {{ '%02d' % (d[18] % 256 | int(0)) }}:{{ '%02d' % (d[18] / 256 | int(0)) }}
          icon: mdi:clock-end
          availability: "{{ state_attr('sensor.solax_local_settings','Data') is not none }}"
