octopus_saving_sessions_input_select:
  input_select:
    # Octopus saving sessions
    saving_session_today:
      name: Saving Session Today
      options:
        - "yes"
        - "no"
        - manual
