octopus_saving_sessions_input_datetime:
  input_datetime:
    #########################################
    #Date of when theres free electric from Octopus
    # v4.    Free electric re implemented
    # v2.1.3 Removed octopus_free_electricity
    #        Added Octopus Free Electricity Start
    #        Added Octopus Free Electricity Stop
    #########################################

    octopus_free_electricity_start:
      name: Octopus Free Electricity Start
      has_date: true
      has_time: true
      icon: mdi:calendar

    octopus_free_electricity_stop:
      name: Octopus Free Electricity Stop
      has_date: true
      has_time: true
      icon: mdi:calendar

    octopus_free_electricity_prep:
      name: Export Battery @Time to Target SoC
      has_date: false
      has_time: true
      icon: mdi:clock

    #Octopus Saving Session
    saving_session_start:
      name: Octopus Saving Session Start
      has_date: true
      has_time: true
      icon: mdi:clock-digital

    #Octopus Saving Session
    saving_session_end:
      name: Octopus Saving Session End
      has_date: true
      has_time: true
      icon: mdi:clock-digital
