###############################################
# Replace octopus account number z_ZZZZZZZZ
###############################################
octopus_saving_sessions_templates:
  template:
    ######################################################
    # Octopus free/saving sensors
    # v4.    Plannning to removed saving sessions because they are pointless
    #.       Refined free sessions to new IOG tariff as of 4/8/2025
    # v2.1.3 moved tariff switching for free electric to this package
    # v2.1.2 Enhancements to Free Electric
    #        Enhancements to saving sessions:
    #        1. Automation 6003 is not required anymore
    #        2. Automation 6002 Options to limit prep time and prep SoC
    #        3. Automation 6002 Added checking during prep to turn off
    #           charge period 2 once prep SoC is reached
    #        4. Automation 6002 clean up and simplification
    #
    ######################################################
    # Octopus Saving Session
    - trigger:
        - trigger: time_pattern
          minutes: /30
        - trigger: state
          entity_id: binary_sensor.octopus_energy_z_ZZZZZZZZ_octoplus_saving_sessions
          not_to:
            - unavailable
            - unknown
        - trigger: state
          entity_id: binary_sensor.octopus_energy_z_ZZZZZZZZ_octoplus_saving_sessions
          attribute: next_joined_event_start
      sensor:
        - name: "Octopus - Is there a Saving Session today?"
          unique_id: octopus_is_there_a_saving_session_today
          state: >
            {% if state_attr('binary_sensor.octopus_energy_z_ZZZZZZZZ_octoplus_saving_sessions','current_joined_event_start') != 'unknown'%}
            {% set current_event = state_attr('binary_sensor.octopus_energy_z_ZZZZZZZZ_octoplus_saving_sessions','current_joined_event_start') %} 
            {% set next_event =state_attr('binary_sensor.octopus_energy_z_ZZZZZZZZ_octoplus_saving_sessions','next_joined_event_start') %} 
            {% set upcoming_event = current_event if (current_event != None) else next_event %} 
            {{ 'yes' if (upcoming_event !=None and upcoming_event.strftime('%j') == now().strftime('%j')) else 'no' }}
            {%else%}
            {% set current_event =None %} 
            {% set next_event =None %} 
            {{'no'}}
            {%endif%}
          attributes:
            session_start: >
              {% if state_attr('binary_sensor.octopus_energy_z_ZZZZZZZZ_octoplus_saving_sessions','current_joined_event_start') != 'unknown'%}
              {% set current_event = state_attr('binary_sensor.octopus_energy_z_ZZZZZZZZ_octoplus_saving_sessions','current_joined_event_start') %} 
              {% set next_event =state_attr('binary_sensor.octopus_energy_z_ZZZZZZZZ_octoplus_saving_sessions','next_joined_event_start') %} 
              {%else%}
              {% set current_event =None %} 
              {% set next_event =None %} 
              {%endif%}
              {% set upcoming_event = current_event if (current_event != None) else next_event %} 
              {{ (now() + timedelta(days=7)).strftime('%Y-%m-%d 00:00:00') if (upcoming_event == None) else upcoming_event}}
            session_end: >
              {% if state_attr('binary_sensor.octopus_energy_z_ZZZZZZZZ_octoplus_saving_sessions','current_joined_event_end') != 'unknown'%}
              {% set current_event_end = state_attr('binary_sensor.octopus_energy_z_ZZZZZZZZ_octoplus_saving_sessions','current_joined_event_end') %} 
              {% set next_event_end =state_attr('binary_sensor.octopus_energy_z_ZZZZZZZZ_octoplus_saving_sessions','next_joined_event_end')   %} 
              {%else%}
              {% set current_event_end =None %} 
              {% set next_event_end =None %} 
              {%endif%}
              {% set upcoming_event_end = current_event_end if (current_event_end != None) else next_event_end %} 
              {{ (now() + timedelta(days=7)).strftime('%Y-%m-%d 01:00:00') if (upcoming_event_end == None) else upcoming_event_end}}

    # Free electric
    # - trigger:
    #     - trigger: time_pattern
    #       minutes: /30
    #     - trigger: state
    #       entity_id: binary_sensor.octopus_energy_z_ZZZZZZZZ_octoplus_free_electricity_session
    #       not_to:
    #         - unavailable
    #         - unknown
    #     - trigger: state
    #       entity_id: binary_sensor.octopus_energy_z_ZZZZZZZZ_octoplus_free_electricity_session
    #       attribute: next_event_start
    #   sensor:
    #     - name: "Octopus - Is there Free Electric today?"
    #       unique_id: octopus_is_there_free_electric_today
    #       state: >

    ######################################################
    #Octopus free electric start
    ######################################################
    - sensor:
        - name: Octopus Free Electricity Start
          unique_id: octopus_free_electricity_start
          device_class: "timestamp"
          state: >
            {{as_datetime(state_attr('input_datetime.octopus_free_electricity_start','timestamp')-120)|as_local}}

    ######################################################
    #Octopus free electric stop
    ######################################################
    - sensor:
        - name: Octopus Free Electric Stop
          unique_id: octopus_free_electric_stop
          device_class: "timestamp"
          state: >
            {{as_datetime(state_attr('input_datetime.octopus_free_electricity_stop','timestamp'))|as_local}}

    ######################################################
    # binary_sensor.free_electricity_today
    ######################################################
    - binary_sensor:
        - name: Free Electricity Today
          unique_id: free_electricity_today
          state: >
            {% set event = state_attr('event.octopus_energy_z_ZZZZZZZZ_octoplus_free_electricity_session_events','events')|last %} 
            {% set event_start = event['start'] %}
            {% set event_end = event['end'] %}
            {%if states('automation.octopus_free_electric_automation') == 'on' and 
            today_at()|as_timestamp ==  (event_start|as_datetime|as_local).date()|as_timestamp 
            and now()|as_timestamp <= event_end|as_timestamp %}
              {{true}}
            {%else%}
              {{false}}
            {%endif%}
          attributes:
            session_start: >
                {% set event = state_attr('event.octopus_energy_z_ZZZZZZZZ_octoplus_free_electricity_session_events','events')|last %} 
                {% set event_start = event['start'] %}
                {{ event_start|as_datetime|as_local }}
            session_end: >
                {% set event = state_attr('event.octopus_energy_z_ZZZZZZZZ_octoplus_free_electricity_session_events','events')|last %} 
                {% set event_end = event['end'] %}
                {{ event_end|as_datetime|as_local }}
            duration: >
                {% set event = state_attr('event.octopus_energy_z_ZZZZZZZZ_octoplus_free_electricity_session_events','events')|last %} 
                {% set event_duration = event['duration_in_minutes'] %}
                {{ event_duration|int}}

    - trigger:
        - trigger: state
          entity_id: binary_sensor.free_electricity_today
          attribute: session_start
          not_to:
            - unavailable
            - unknown
      action:
        - service: input_datetime.set_datetime
          target:
            entity_id: input_datetime.octopus_free_electricity_start
          data:
            datetime: >
              {% set event = state_attr('event.octopus_energy_z_ZZZZZZZZ_octoplus_free_electricity_session_events','events')|last %} 
              {% set event_start = event['start'] %}
              {{ (event_start)|as_datetime|as_local}}
        - service: input_datetime.set_datetime
          target:
            entity_id: input_datetime.octopus_free_electricity_stop
          data:
            datetime: >
              {% set event = state_attr('event.octopus_energy_z_ZZZZZZZZ_octoplus_free_electricity_session_events','events')|last %} 
              {% set event_end = event['end'] %}
              {{ (event_end)|as_datetime|as_local}}

    ######################################################

    ######################################################
    # Generate tariff events and selects utility meter
    # settings for free electric sessions
    ######################################################
    - trigger:
        - trigger: time
          at: sensor.octopus_free_electricity_start
      action:
        - event: octopus_tariff
          event_data:
            tariff: "free"
            time: >
              {{now()|as_datetime}}
        - service: select.select_option
          data:
            entity_id: select.daily_grid_import
            option: "free"
        - service: select.select_option
          data:
            entity_id: select.monthly_grid_import
            option: "free"

    - trigger:
        - trigger: state
          entity_id: binary_sensor.free_electricity_today
          from: "on"
          to: "off"
          for:
            minutes: 2
      action:
        - event: octopus_tariff
          event_data:
            tariff: >
              {% if states('binary_sensor.octopus_energy_z_ZZZZZZZZ_intelligent_dispatching') == 'on' %}
                {{"offpeak"}}
              {% else %}
                {{"peak"}}
              {% endif %}
            time: >
              {{now()|as_datetime}}
        - service: select.select_option
          data:
            entity_id: select.daily_grid_import
            option: >
              {% if states('binary_sensor.octopus_energy_z_ZZZZZZZZ_intelligent_dispatching') == 'on' %}
                {{"offpeak"}}
              {% else %}
                {{"peak"}}
              {% endif %}
        - service: select.select_option
          data:
            entity_id: select.monthly_grid_import
            option: >
              {% if states('binary_sensor.octopus_energy_z_ZZZZZZZZ_intelligent_dispatching') == 'on' %}
                {{"offpeak"}}
              {% else %}
                {{"peak"}}
              {% endif %}
    ######################################################
